//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colmart
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColmartProducts
    {
        public int fProductStockID { get; set; }
        public string Branch { get; set; }
        public string StyleCode { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string ImageURL { get; set; }
        public string Size { get; set; }
        public int SizeOrdinal { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Qty_OnHand { get; set; }
    }
}
