//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colmart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductSizes
    {
        public int iProductSizeID { get; set; }
        public System.DateTime dtAdded { get; set; }
        public int iAddedBy { get; set; }
        public Nullable<System.DateTime> dtEdited { get; set; }
        public int iEditedBy { get; set; }
        public string strSize { get; set; }
        public double dblPrice { get; set; }
        public int iQuantityAvailable { get; set; }
        public int iProductID { get; set; }
        public bool bIsDeleted { get; set; }
    
        public virtual tblProducts tblProducts { get; set; }
    }
}
