//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class WebSalesOrderQueryCriteria {
    
    private string pONumberField;
    
    private bool simpleResultsField;
    
    private bool simpleResultsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PONumber {
        get {
            return this.pONumberField;
        }
        set {
            this.pONumberField = value;
        }
    }
    
    /// <remarks/>
    public bool SimpleResults {
        get {
            return this.simpleResultsField;
        }
        set {
            this.simpleResultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SimpleResultsSpecified {
        get {
            return this.simpleResultsFieldSpecified;
        }
        set {
            this.simpleResultsFieldSpecified = value;
        }
    }
}
