//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class WebSalesOrder {
    
    private string commentsField;
    
    private AddressDetail deliveryDetailField;
    
    private System.Nullable<int> deliveryMethodIDField;
    
    private bool deliveryMethodIDFieldSpecified;
    
    private string deliveryMethodNameField;
    
    private System.Nullable<int> entitlementIDField;
    
    private bool entitlementIDFieldSpecified;
    
    private System.Nullable<bool> isGiftField;
    
    private bool isGiftFieldSpecified;
    
    private System.Nullable<bool> isXStockField;
    
    private bool isXStockFieldSpecified;
    
    private WebSalesOrderDetail[] lineItemsField;
    
    private string pONumberField;
    
    private System.Nullable<int> paymentMethodIDField;
    
    private bool paymentMethodIDFieldSpecified;
    
    private System.Nullable<bool> printInvoiceField;
    
    private bool printInvoiceFieldSpecified;
    
    private System.Nullable<System.DateTime> requiredDateField;
    
    private bool requiredDateFieldSpecified;
    
    private int salesOrderIDField;
    
    private bool salesOrderIDFieldSpecified;
    
    private string specialInstructionsField;
    
    private System.Nullable<int> statusIDField;
    
    private bool statusIDFieldSpecified;
    
    private string trackNoField;
    
    private string webCustomerNameField;
    
    private System.Nullable<bool> webSaleField;
    
    private bool webSaleFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public AddressDetail DeliveryDetail {
        get {
            return this.deliveryDetailField;
        }
        set {
            this.deliveryDetailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> DeliveryMethodID {
        get {
            return this.deliveryMethodIDField;
        }
        set {
            this.deliveryMethodIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveryMethodIDSpecified {
        get {
            return this.deliveryMethodIDFieldSpecified;
        }
        set {
            this.deliveryMethodIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string DeliveryMethodName {
        get {
            return this.deliveryMethodNameField;
        }
        set {
            this.deliveryMethodNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> EntitlementID {
        get {
            return this.entitlementIDField;
        }
        set {
            this.entitlementIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EntitlementIDSpecified {
        get {
            return this.entitlementIDFieldSpecified;
        }
        set {
            this.entitlementIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsGift {
        get {
            return this.isGiftField;
        }
        set {
            this.isGiftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsGiftSpecified {
        get {
            return this.isGiftFieldSpecified;
        }
        set {
            this.isGiftFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> IsXStock {
        get {
            return this.isXStockField;
        }
        set {
            this.isXStockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsXStockSpecified {
        get {
            return this.isXStockFieldSpecified;
        }
        set {
            this.isXStockFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public WebSalesOrderDetail[] LineItems {
        get {
            return this.lineItemsField;
        }
        set {
            this.lineItemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PONumber {
        get {
            return this.pONumberField;
        }
        set {
            this.pONumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> PaymentMethodID {
        get {
            return this.paymentMethodIDField;
        }
        set {
            this.paymentMethodIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PaymentMethodIDSpecified {
        get {
            return this.paymentMethodIDFieldSpecified;
        }
        set {
            this.paymentMethodIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> PrintInvoice {
        get {
            return this.printInvoiceField;
        }
        set {
            this.printInvoiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrintInvoiceSpecified {
        get {
            return this.printInvoiceFieldSpecified;
        }
        set {
            this.printInvoiceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> RequiredDate {
        get {
            return this.requiredDateField;
        }
        set {
            this.requiredDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiredDateSpecified {
        get {
            return this.requiredDateFieldSpecified;
        }
        set {
            this.requiredDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int SalesOrderID {
        get {
            return this.salesOrderIDField;
        }
        set {
            this.salesOrderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SalesOrderIDSpecified {
        get {
            return this.salesOrderIDFieldSpecified;
        }
        set {
            this.salesOrderIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SpecialInstructions {
        get {
            return this.specialInstructionsField;
        }
        set {
            this.specialInstructionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> StatusID {
        get {
            return this.statusIDField;
        }
        set {
            this.statusIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusIDSpecified {
        get {
            return this.statusIDFieldSpecified;
        }
        set {
            this.statusIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TrackNo {
        get {
            return this.trackNoField;
        }
        set {
            this.trackNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string WebCustomerName {
        get {
            return this.webCustomerNameField;
        }
        set {
            this.webCustomerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> WebSale {
        get {
            return this.webSaleField;
        }
        set {
            this.webSaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WebSaleSpecified {
        get {
            return this.webSaleFieldSpecified;
        }
        set {
            this.webSaleFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class AddressDetail {
    
    private int addressDetailIDField;
    
    private bool addressDetailIDFieldSpecified;
    
    private string addressLine1Field;
    
    private string addressLine2Field;
    
    private string altNumberField;
    
    private string cityField;
    
    private string companyField;
    
    private string countryField;
    
    private string emailField;
    
    private string fullNameField;
    
    private string mobileField;
    
    private string phoneField;
    
    private string postCodeField;
    
    private string provinceField;
    
    /// <remarks/>
    public int AddressDetailID {
        get {
            return this.addressDetailIDField;
        }
        set {
            this.addressDetailIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AddressDetailIDSpecified {
        get {
            return this.addressDetailIDFieldSpecified;
        }
        set {
            this.addressDetailIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AddressLine1 {
        get {
            return this.addressLine1Field;
        }
        set {
            this.addressLine1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AddressLine2 {
        get {
            return this.addressLine2Field;
        }
        set {
            this.addressLine2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AltNumber {
        get {
            return this.altNumberField;
        }
        set {
            this.altNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Mobile {
        get {
            return this.mobileField;
        }
        set {
            this.mobileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PostCode {
        get {
            return this.postCodeField;
        }
        set {
            this.postCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class WebSalesOrderDetail {
    
    private System.Nullable<int> cNTypeIDField;
    
    private bool cNTypeIDFieldSpecified;
    
    private string commentField;
    
    private System.Nullable<decimal> commissionField;
    
    private bool commissionFieldSpecified;
    
    private System.Nullable<decimal> discountField;
    
    private bool discountFieldSpecified;
    
    private System.Nullable<System.DateTime> dueDateField;
    
    private bool dueDateFieldSpecified;
    
    private System.Nullable<decimal> exRateField;
    
    private bool exRateFieldSpecified;
    
    private System.Nullable<System.DateTime> invoiceDateField;
    
    private bool invoiceDateFieldSpecified;
    
    private string invoiceNumberField;
    
    private string invoiceReferenceField;
    
    private System.Nullable<bool> invoiceSubCustomerField;
    
    private bool invoiceSubCustomerFieldSpecified;
    
    private System.Nullable<decimal> invoiceUnitsField;
    
    private bool invoiceUnitsFieldSpecified;
    
    private System.Nullable<int> productStockIDField;
    
    private bool productStockIDFieldSpecified;
    
    private string referenceField;
    
    private System.Nullable<int> sODetailIDField;
    
    private bool sODetailIDFieldSpecified;
    
    private System.Nullable<int> salesOrderIDField;
    
    private bool salesOrderIDFieldSpecified;
    
    private System.Nullable<decimal> sellingPriceField;
    
    private bool sellingPriceFieldSpecified;
    
    private System.Nullable<int> statusIDField;
    
    private bool statusIDFieldSpecified;
    
    private string thirdPartyBarcodeField;
    
    private System.Nullable<decimal> unitsField;
    
    private bool unitsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> CNTypeID {
        get {
            return this.cNTypeIDField;
        }
        set {
            this.cNTypeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CNTypeIDSpecified {
        get {
            return this.cNTypeIDFieldSpecified;
        }
        set {
            this.cNTypeIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Commission {
        get {
            return this.commissionField;
        }
        set {
            this.commissionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CommissionSpecified {
        get {
            return this.commissionFieldSpecified;
        }
        set {
            this.commissionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Discount {
        get {
            return this.discountField;
        }
        set {
            this.discountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DiscountSpecified {
        get {
            return this.discountFieldSpecified;
        }
        set {
            this.discountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DueDate {
        get {
            return this.dueDateField;
        }
        set {
            this.dueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DueDateSpecified {
        get {
            return this.dueDateFieldSpecified;
        }
        set {
            this.dueDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> ExRate {
        get {
            return this.exRateField;
        }
        set {
            this.exRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExRateSpecified {
        get {
            return this.exRateFieldSpecified;
        }
        set {
            this.exRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> InvoiceDate {
        get {
            return this.invoiceDateField;
        }
        set {
            this.invoiceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvoiceDateSpecified {
        get {
            return this.invoiceDateFieldSpecified;
        }
        set {
            this.invoiceDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string InvoiceNumber {
        get {
            return this.invoiceNumberField;
        }
        set {
            this.invoiceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string InvoiceReference {
        get {
            return this.invoiceReferenceField;
        }
        set {
            this.invoiceReferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> InvoiceSubCustomer {
        get {
            return this.invoiceSubCustomerField;
        }
        set {
            this.invoiceSubCustomerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvoiceSubCustomerSpecified {
        get {
            return this.invoiceSubCustomerFieldSpecified;
        }
        set {
            this.invoiceSubCustomerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> InvoiceUnits {
        get {
            return this.invoiceUnitsField;
        }
        set {
            this.invoiceUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvoiceUnitsSpecified {
        get {
            return this.invoiceUnitsFieldSpecified;
        }
        set {
            this.invoiceUnitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> ProductStockID {
        get {
            return this.productStockIDField;
        }
        set {
            this.productStockIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProductStockIDSpecified {
        get {
            return this.productStockIDFieldSpecified;
        }
        set {
            this.productStockIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> SODetailID {
        get {
            return this.sODetailIDField;
        }
        set {
            this.sODetailIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SODetailIDSpecified {
        get {
            return this.sODetailIDFieldSpecified;
        }
        set {
            this.sODetailIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> SalesOrderID {
        get {
            return this.salesOrderIDField;
        }
        set {
            this.salesOrderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SalesOrderIDSpecified {
        get {
            return this.salesOrderIDFieldSpecified;
        }
        set {
            this.salesOrderIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> SellingPrice {
        get {
            return this.sellingPriceField;
        }
        set {
            this.sellingPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SellingPriceSpecified {
        get {
            return this.sellingPriceFieldSpecified;
        }
        set {
            this.sellingPriceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> StatusID {
        get {
            return this.statusIDField;
        }
        set {
            this.statusIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusIDSpecified {
        get {
            return this.statusIDFieldSpecified;
        }
        set {
            this.statusIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ThirdPartyBarcode {
        get {
            return this.thirdPartyBarcodeField;
        }
        set {
            this.thirdPartyBarcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.DTO", IsNullable=true)]
public partial class ArrayOfWebSalesOrderDetail {
    
    private WebSalesOrderDetail[] webSalesOrderDetailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("WebSalesOrderDetail", IsNullable=true)]
    public WebSalesOrderDetail[] WebSalesOrderDetail {
        get {
            return this.webSalesOrderDetailField;
        }
        set {
            this.webSalesOrderDetailField = value;
        }
    }
}
