//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8937
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSync.EAI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(iSync.EAI.CustomRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ActionField;
        
        private string IdentifierField;
        
        private string InstanceField;
        
        private string MessageTypeField;
        
        private string MessageXmlField;
        
        private System.DateTime PublishDateField;
        
        private string SessionKeyField;
        
        private string SourceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Instance
        {
            get
            {
                return this.InstanceField;
            }
            set
            {
                this.InstanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MessageXml
        {
            get
            {
                return this.MessageXmlField;
            }
            set
            {
                this.MessageXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime PublishDate
        {
            get
            {
                return this.PublishDateField;
            }
            set
            {
                this.PublishDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionKey
        {
            get
            {
                return this.SessionKeyField;
            }
            set
            {
                this.SessionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomRequest", Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI")]
    public partial class CustomRequest : iSync.EAI.Request
    {
        
        private iSync.EAI.CustomXml.Mapping[] MappingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iSync.EAI.CustomXml.Mapping[] Mappings
        {
            get
            {
                return this.MappingsField;
            }
            set
            {
                this.MappingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(iSync.EAI.Response))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ResponseTextField;
        
        private bool SuccessflagField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseText
        {
            get
            {
                return this.ResponseTextField;
            }
            set
            {
                this.ResponseTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successflag
        {
            get
            {
                return this.SuccessflagField;
            }
            set
            {
                this.SuccessflagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI")]
    public partial class Response : iSync.EAI.ResponseBase
    {
        
        private string ActionField;
        
        private string IdentifierField;
        
        private string InstanceField;
        
        private string MessageTypeField;
        
        private System.DateTime PublishDateField;
        
        private string ResultXmlField;
        
        private string SourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instance
        {
            get
            {
                return this.InstanceField;
            }
            set
            {
                this.InstanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PublishDate
        {
            get
            {
                return this.PublishDateField;
            }
            set
            {
                this.PublishDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultXml
        {
            get
            {
                return this.ResultXmlField;
            }
            set
            {
                this.ResultXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
    }
}
namespace iSync.EAI.CustomXml
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mapping", Namespace="http://schemas.datacontract.org/2004/07/iSync.EAI.CustomXml")]
    public partial class Mapping : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ArgumentsField;
        
        private string NoteField;
        
        private string SourceField;
        
        private string SyncFieldField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Arguments
        {
            get
            {
                return this.ArgumentsField;
            }
            set
            {
                this.ArgumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SyncField
        {
            get
            {
                return this.SyncFieldField;
            }
            set
            {
                this.SyncFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMessageService")]
public interface IMessageService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Execute", ReplyAction="http://tempuri.org/IMessageService/ExecuteResponse")]
    iSync.EAI.Response Execute(iSync.EAI.Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/ExecuteCustom", ReplyAction="http://tempuri.org/IMessageService/ExecuteCustomResponse")]
    iSync.EAI.Response ExecuteCustom(iSync.EAI.CustomRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetAvailableOperations", ReplyAction="http://tempuri.org/IMessageService/GetAvailableOperationsResponse")]
    string[] GetAvailableOperations();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/Login", ReplyAction="http://tempuri.org/IMessageService/LoginResponse")]
    string Login(string username, string password);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMessageServiceChannel : IMessageService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MessageServiceClient : System.ServiceModel.ClientBase<IMessageService>, IMessageService
{
    
    public MessageServiceClient()
    {
    }
    
    public MessageServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public iSync.EAI.Response Execute(iSync.EAI.Request request)
    {
        return base.Channel.Execute(request);
    }
    
    public iSync.EAI.Response ExecuteCustom(iSync.EAI.CustomRequest request)
    {
        return base.Channel.ExecuteCustom(request);
    }
    
    public string[] GetAvailableOperations()
    {
        return base.Channel.GetAvailableOperations();
    }
    
    public string Login(string username, string password)
    {
        return base.Channel.Login(username, password);
    }
}
