//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colmart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCMSUserAccess
    {
        public int iCMSUserAccessID { get; set; }
        public System.DateTime dtAdded { get; set; }
        public int iAddedBy { get; set; }
        public Nullable<System.DateTime> dtEdited { get; set; }
        public int iEditedBy { get; set; }
        public int iCMSUserID { get; set; }
        public int iCMSPageID { get; set; }
        public bool bIsRead { get; set; }
        public bool bIsWrite { get; set; }
        public bool bIsDeleted { get; set; }
    
        public virtual tblCMSPages tblCMSPages { get; set; }
        public virtual tblCMSUsers tblCMSUsers { get; set; }
    }
}
