//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colmart
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeadWishlists
    {
        public int iLeadWishlistID { get; set; }
        public Nullable<System.DateTime> dtAdded { get; set; }
        public Nullable<int> iAddedBy { get; set; }
        public Nullable<System.DateTime> dtEdited { get; set; }
        public Nullable<int> iEditedBy { get; set; }
        public int iProductID { get; set; }
        public int iProductSizeID { get; set; }
        public int iProductQuantity { get; set; }
        public int iLeadID { get; set; }
        public bool bIsDeleted { get; set; }
    
        public virtual tblLeads tblLeads { get; set; }
        public virtual tblProducts tblProducts { get; set; }
        public virtual tblProductSizes tblProductSizes { get; set; }
    }
}
